### ISSUE TITLE
Not safe to assume table names

### ISSUE THREAD

**Issue by robmhoward** [OfficeDev/Excel-Add-in-JS-CollegeBudgetTracker#1]
You make assumptions about the name of tables you're creating in several cases.  You should be able to create a local variable that captures the resulting table instead, and use that to do the config.

**Comment by robmhoward** [comment]
If you need to use the table name rather than a local variable, you should set them explicitly and catch the case where the set fails.

**Comment by umasubra** [comment]
Sorry Rob, I had incorporated all your fixes long time ago, just forgot to close the issues. Closing them now.
