### ISSUE TITLE
Getting ranges over and over again

### ISSUE THREAD

**Issue by robmhoward** [OfficeDev/Excel-Add-in-JS-CollegeBudgetTracker#4]
You have quite a few spots where you're getting the same range over and over again.  It's not really a big deal, but you could just get the range once, store it in a local variable, and then use the local variable to set the values, format, etc.  The nice thing about doing it that way is that it's easier to adjust the range locations if need to later.  You can also do things like address rows, cells, or offsets within a range by index, making it easier to use a single static range address to configure a block of adjacent cells.  

https://github.com/OfficeDev/Excel-Add-in-JS-CollegeBudgetTracker/blob/master/Text%20Editor/Home.js#L34

**Comment by umasubra** [comment]
Sorry Rob, I had incorporated all your fixes long time ago, just forgot to close the issues. Closing them now.

**Comment by umasubra** [comment]
Closing the issue now as they have been fixed.
